name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Set up environment variables
        run: |
          echo "NEXT_PUBLIC_API_URL=http://localhost:8000" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FACTCHECK_API_KEY=dummy-key" >> $GITHUB_ENV
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test 